blog/article/urls.py
from django.conf.urls import url
from article import views


urlpatterns = [
    url(r'^$', views.article, name='article'),
    url(r'^articleCreate/$', views.articleCreate, name='articleCreate'),
    url(r'^articleRead/(?P<articleId>[0-9]+)/$', views.articleRead, name='articleRead'),
    url(r'^articleUpdate/(?P<articleId>[0-9]+)/$', views.articleUpdate, name='articleUpdate'),
    url(r'^articleDelete/(?P<articleId>[0-9]+)/$', views.articleDelete, name='articleDelete'),
    url(r'^articleSearch/$', views.articleSearch, name='articleSearch'),
    url(r'^articleLike/<int:articleId>/$', views.articleLike, name='articleLike'),
    url(r'^commentCreate/<int:articleId>/$', views.commentCreate, name='commentCreate'),
    url(r'^commentUpdate/<int:commentId>/$', views.commentUpdate, name='commentUpdate'),
    
]

blog/blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^article/', include('article.urls', namespace='article')),
    url(r'^main/', include('main.urls', namespace='main')),
    url(r'^.*', include('main.urls')),
]

blog/article/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField()
    pubDateTime = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-pubDateTime']


class Comment(models.Model):
    article = models.ForeignKey(Article)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=128)
    pubDateTime = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.article.title + '-' + str(self.id)
    class Meta:
        ordering = ['-pubDateTime']

blog/article/forms.py
from django import forms
from article.models import Article


class ArticleForm(forms.ModelForm):
    title = forms.CharField(label='標題', max_length=128)
    content = forms.CharField(label='內容', widget=forms.Textarea)

    class Meta:
        model = Article
        fields = ['title', 'content']

blog/article/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models.query_utils import Q
from article.forms import ArticleForm
from article.models import Article, Comment


def article(request):
    '''
    Render the article page
    '''
    articles = Article.objects.all()
    itemList = []
    for article in articles:
        items = [article]
        items.extend(list(Comment.objects.filter(article=article)))
        itemList.append(items)
    context = {'itemList':itemList}
    return render(request, 'article/article.html', context)



def articleCreate(request):
    '''
    Create a new article instance
        1. If method is GET, render an empty form
        2. If method is POST, perform form validation and display error messages if the form is invalid
        3. Save the form to the model and redirect the user to the article page
    '''
    # TODO: finish the code
    template = 'article/articleCreateUpdate.html'
    if request.method == 'GET':
        return render(request, template, {'articleForm':ArticleForm()})
    # POST
    articleForm = ArticleForm(request.POST)
    if not articleForm.is_valid():
        return render(request, template, {'articleForm':articleForm})
    articleForm.save()
    messages.success(request, '文章已新增')
    return redirect('article:article')


def articleRead(request, articleId):
    '''
    Read an article
        1. Get the "article" instance using "articleId"; redirect to the 404 page if not found
        2. Render the articleRead template with the article instance and its
           associated comments
    '''
    article = get_object_or_404(Article, id=articleId)
    context = {
        'article': article,
        'comments': Comment.objects.filter(article=article)
    }
    return render(request, 'article/articleRead.html', context)

def articleUpdate(request, articleId):
    '''
    Update the article instance:
        1. Get the article to update; redirect to 404 if not found
        2. Render a bound form if the method is GET
        3. If the form is valid, save it to the model, otherwise render a
           bound form with error messages
    '''
    article = get_object_or_404(Article, id=articleId)
    template = 'article/articleCreateUpdate.html'
    if request.method == 'GET':
        articleForm = ArticleForm(instance=article)
        return render(request, template, {'articleForm':articleForm})
    # POST
    articleForm = ArticleForm(request.POST, instance=article)
    if not articleForm.is_valid():
        return render(request, template, {'articleForm':articleForm})
    articleForm.save()
    messages.success(request, '文章已修改') 
    return redirect('article:articleRead', articleId=articleId)
def articleDelete(request, articleId):
    if request.method == 'GET':
        return article(request)
    # POST
    articleToDelete = get_object_or_404(Article, id=articleId)
    articleToDelete.delete()
    messages.success(request, '文章已刪除')  
    return redirect('article:article')
def articleSearch(request):
    '''
    Search for articles:
        1. Get the "searchTerm" from the HTML page
        2. Use "searchTerm" for filtering
    '''
    searchTerm = request.GET.get('searchTerm')
    articles = Article.objects.filter(Q(title__icontains=searchTerm) |
                                      Q(content__icontains=searchTerm))
    context = {'articles':articles, 'searchTerm':searchTerm} 
    return render(request, 'article/articleSearch.html', context)


def articleLike(request, articleId):
    '''
    Add the user to the 'likes' field:
        1. Get the article; redirect to 404 if not found
        2. If the user does not exist in the "likes" field, add him/her
        3. Finally, call articleRead() function to render the article
    '''
    article = get_object_or_404(Article, id=articleId)
    if request.user not in article.likes.all():
        article.likes.add(request.user)
    return articleRead(request, articleId)


def commentCreate(request, articleId):
    '''
    Create a comment for an article:
        1. Get the "comment" from the HTML form
        2. Store it to database
    '''
    if request.method == 'GET':
        return articleRead(request, articleId)
    # POST
    comment = request.POST.get('comment')
    if comment:
        comment = comment.strip()
    if not comment:
        return redirect('article:articleRead', articleId=articleId)
    article = get_object_or_404(Article, id=articleId)
    Comment.objects.create(article=article, user=request.user, content=comment)
    return redirect('article:articleRead', articleId=articleId)

def commentUpdate(request, commentId):
    '''
    Update a comment:
        1. Get the comment to update and its article; redirect to 404 if not found
        2. If comment is empty, delete the comment
        3. Else update the comment
    '''
    commentToUpdate = get_object_or_404(Comment, id=commentId)
    article = get_object_or_404(Article, id=commentToUpdate.article.id)
    if request.method == 'GET':
        return articleRead(request, article.id)

    # POST    
    if commentToUpdate.user != request.user:
        messages.error(request, '無修改權限')
        return articleRead(request, article.id)
    comment = request.POST.get('comment', '').strip()
    if not comment:
        commentToUpdate.delete()
    else:
        commentToUpdate.content = comment
        commentToUpdate.save()
    return redirect('article:articleRead', articleId=article.id)

blog/article/templates/article/article.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" href="{% static 'article/css/article.css' %}">
  {% endblock %}
{% block heading %}歡迎蒞臨{% endblock %}
{% block content %}
    {% include 'article/searchForm.html' %}
    <p class="inlineBlock"><a class="btn" href="{% url 'article:articleCreate' %}">新增文章</a></p>
    <br><br><hr>
    {% for items in itemList %}
      {% for item in items %}
        {% if forloop.first %}
          <h3 class="inlineBlock"><a href="{% url 'article:articleRead' item.id %}">{{ item.title }}</a></h3>
          <form class="inlineBlock" method="post" action="{% url 'article:articleDelete' item.id %}">
        {% csrf_token %}
        <input class="btn deleteConfirm" type="submit" value="刪除">
      </form>
          <p>發表時間：<a href="{% url 'article:articleRead' item.id %}">{{ item.title }}</a></p>
          <div class="articleContent">{{ item.content|linebreaks|truncatechars_html:30 }}</div>
        <p class=like>
          <img id=like src="{% static 'main/img/like.png' %}" alt="Like"> {{ item.likes.count }}
        </p>
        {% else %}
          <div class="commentDiv">
          <span class="commentAuthor">{{ item.user.profile.fullName }}</span>
            <span class="comment">{{ item.content }}</span><br>
            <span class="commentTime">{{ item.pubDateTime|date:'m月d日 H:i' }}</span>
          </div>
        {% endif %}
      {% endfor %}
      <hr>
    {% endfor %}
    {% endblock %}
{% block script %}
  <script src={% static 'main/js/deleteConfirm.js' %}></script>
{% endblock %}

blog/article/templates/article/articleCreate.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>部落格</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'article/css/article.css' %}">
  </head>
  <body>
    {% include 'main/menu.html' %}
    <h2>新增文章</h2>
    <form method="post" action="{% url 'article:articleCreate' %}">
      {% csrf_token %}
      {{ articleForm.as_p }}
      <input type="submit" value="送出">
    </form>
  </body>
</html>

blog/article/templates/article/articleCreateUpdate.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
{% endblock %}
{% block heading %}
  {% if articleForm.instance.id %}
    修改文章
  {% else %}
    新增文章
  {% endif %}
{% endblock %}
{% block content %}
    {% if articleForm.instance.id %}

    <form method="post" action="{% url 'article:articleUpdate' articleForm.instance.id %}">
  {% else %}
 
    <form method="post" action="{% url 'article:articleCreate' %}">
    {% endif %}
      {% csrf_token %}
      {{ articleForm.as_p }}
      <input class="btn" type="submit" value="送出">
      <a class="btn" href="{% url 'article:article' %}">放棄</a>
    </form>
 {% endblock %}

blog/article/templates/article/articleRead.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}
<link rel="stylesheet" href="{% static 'article/css/article.css' %}">
{% endblock %}
{% block heading %}閱讀文章{% endblock %}
{% block content %}
    <h3 class="inlineBlock">{{ article.title }}</h3>
    <a class="btn inlineBlock" href="{% url 'article:articleUpdate' article.id %}">修改</a>
    <p>發表時間：{{ article.pubDateTime|date:'Y-m-d H:i' }}</p>
    <div class="articleContent">{{ article.content|linebreaks }}</div>
    {% for comment in comments %}
      <div class="commentDiv">
        <span class="commentAuthor">{{ comment.user.profile.fullName }}</span>
        {% if comment.user != user %}
        <span class="comment">{{ comment.content }}</span>
        {% else %}
          <form class="inlineBlock" method="post" action="{% url 'article:commentUpdate' comment.id %}">
            {% csrf_token %}
            <input type="text" name="comment" value="{{ comment.content }}">
            <input class="btn" type="submit" value="修改">
          </form>
        {% endif %}<br>
        <span class="commentTime">{{ comment.pubDateTime|date:'Y-m-d H:i'}}</span>
      </div>
    {% endfor %}
    {% if user.is_authenticated %}
      <br>
      <form method="post" action="{% url 'article:commentCreate' article.id %}">
        {% csrf_token %}
        <input type="text" name="comment"  placeholder="留言 ...">
        <input class="btn" type="submit" value="送出">
      </form>
      <br><br>
    {% endif %}
{% endblock %}

blog/article/templates/article/articleSearch.html
    <!doctype html>
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" href="{% static 'article/css/article.css' %}">
{% endblock %}
{% block heading %}搜尋{% endblock %}
{% block content %}m.html' %}
    <br><br><hr>
    {% if not articles %}
      <p>查無資料</p>
    {% else %}
      <table class="table table-striped table-hover">
        <tr><th>標題</th><th>發表時間</th></tr>
        {% for article in articles %}
        <tr>
          <td><a href="{% url 'article:articleRead' article.id %}">{{ article.title }}</a></td>
          <td>{{ article.pubDateTime|date:'Y-m-d H:i' }}</td>
        </tr>
        {% endfor %}
      </table>
    {% endif %}
{% endblock %}

blog/article/templates/article/searchForm.html
<form class="inlineBlock" action="{% url 'article:articleSearch' %}">
  <input type="text" name="searchTerm" {% if searchTerm %}value="{{ searchTerm }}"{% endif %}>
  <input class="btn" type="submit" value="查詢">
</form>